### ISSUE TITLE
Unable to start MagicMirror

### ISSUE THREAD

**Issue by EspenT** [Jopyth/MMM-Remote-Control#146]
0|mm  | Starting MagicMirror: v2.8.0
0|mm  | Loading config ...
0|mm  | WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:71
0|mm  | 			position: 'bottom_left'
0|mm  | 			^^^^^^^^
0|mm  | SyntaxError: Unexpected identifier
0|mm  |     at new Script (vm.js:74:7)
0|mm  |     at createScript (vm.js:246:10)
0|mm  |     at Object.runInThisContext (vm.js:298:10)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:678:28)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm  |     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
0|mm  |     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm  |     at require (internal/modules/cjs/helpers.js:20:18)

**Comment by EspenT** [comment]
`		{
			module: 'MMM-YrNow',
			position: 'top_right',
			config: {
				locationId: '10-975596',
				showWeatherForecast: true
					}
		},
		
		{
                        module: 'MMM-Remote-Control'
			position: 'bottom_left'
			config: {
                                apiKey: ''
                                         }
                },

`

**Comment by EspenT** [comment]
never mind. missing a ,
