### ISSUE TITLE
Error code EADDRINUSE

### ISSUE THREAD

**Issue by PXNDA1234321** [Jopyth/MMM-Remote-Control#150]
I am getting this error (EADDRINUSE) in Git Bash (I am running MagicMirror on Windows).

`{ Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1492:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:755:11)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080 }`

**Comment by lavolp3** [comment]
This is most probably not realted to this module but to the fact that you have tried to start a second instance of magicmirror.
Do you have pm2 controlling the mirror in the background?

**Comment by ezeholz** [comment]
Hey! Most probably because you have another application running in the port 8080, that's used for display the remote. Anyways, I'm gonna close this issue because it's more than a year old, feel free to open a new one if you have any other question.
