### ISSUE TITLE
Magic Mirror crashes when i put in module

### ISSUE THREAD

**Issue by dritonkb** [Jopyth/MMM-Remote-Control#212]
Hi, when i put in the module in config.js im getting the error:

[2020-09-05 23:00:27.161] [ERROR]  WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:46
			config: {
			^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadConfig (/home/pi/MagicMirror/js/app.js:67:12)
    at App.start (/home/pi/MagicMirror/js/app.js:202:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:126:7)
    at Module._compile (internal/modules/cjs/loader.js:786:30)

is there any fix to this?

**Comment by ezeholz** [comment]
Yep, actually there is a PR for that. But the author don't follow this repo anymore. 

The solution is a comma right before that. You can see it in #149 

Also you can check my fork, where I usually maintain and solve some of the knowns issues with this repo. 

I encourage you to close this issue if I was able to solve it ;D
