### ISSUE TITLE
Remote Control REST API not working

### ISSUE THREAD

**Issue by Anonym-tsk** [Jopyth/MMM-Remote-Control#291]
### OS

Raspbian

### NodeJS Version

10.24.1

### MagicMirror Version

2.23.0

### Remote Control Version

2.3.7

### Did you try using just Remote Control alone with MM?

- [X] I have and the error still happening

### Description

I tried to use remote control integration with my module https://github.com/Anonym-tsk/MMM-go2rtc
I added `REGISTER_API` notification and it works from `/remote.html` interface.
But it doesn't work as REST API (when i open `api/module/:moduleName/:action` url).

### Expected behavior

URL should work as documented: `/api/module/go2rtc/play`

### Current behavior

Look ad my code: https://github.com/Anonym-tsk/MMM-go2rtc/blob/e15362c60fad4d15cce06427a2d04ddb025244b1/MMM-go2rtc.js#L70
1. `path` option doesn't work. I wanted to have url `/api/module/go2rtc`, but working url is `/api/module/module_3_MMM-go2rtc`
2. `/api/module/module_3_MMM-go2rtc` response missed `actions`.
3. Actions not working. `/api/module/module_3_MMM-go2rtc/play` returns error
```
TypeError: Cannot read properties of undefined (reading 'play')
    at Class.answerModuleApi (/home/pi/MagicMirror/modules/MMM-Remote-Control/API/api.js:415:36)
    at /home/pi/MagicMirror/modules/MMM-Remote-Control/API/api.js:273:22
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/MagicMirror/node_modules/express/lib/router/index.js:284:15
    at param (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:365:14)
    at param (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:376:14)
    at param (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:376:14)
    at param (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:421:3)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:280:10)
    at /home/pi/MagicMirror/modules/MMM-Remote-Control/API/api.js:153:13
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:328:13)
```

### Steps to reproduce

Install [MMM-go2rtc](https://github.com/Anonym-tsk/MMM-go2rtc/tree/master) and try to use

### Log

```shell
---------
```

### config.js

```javascript
{
                        module: 'MMM-Remote-Control',
                        config: {
                                customCommand: {},
                                showModuleApiMenu: true,
                                secureEndpoints: false,
                        }
                },
                {
                        module: "MMM-go2rtc",
                        position: "top_left",
                        config: {
                                host: "192.168.10.10",
                                port: "1984",
                                entity: "camera",
                        },
                },
```

**Comment by earlywaff** [comment]
up!

**Comment by kris4ever** [comment]
Hi, any update on this ? Facing the same issue.
Thanks for your help.

**Comment by ezeholz** [comment]
There was an update in the latest release affecting this area. It's possible that this issue has been resolved.

Let me know if you're still facing this issue in the latest update. I'll try to make some time to check it out.
